language: elixir

elixir:
  - 1.11.3
  - 1.10.4

otp_release:
  - '23.2.7'
  - '22.3.4.16'

before_script:
  - mix compile –warnings-as-errors
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" =~ "1.10" ]]; then mix format mix.exs "{config,clients,games,lib,test}/**/*.{ex,exs}" --check-formatted; fi

before_install:
  - sudo apt-get install -y build-essential erlang-dev libmagic-dev
